version: 0.1

phases:
  install:
    commands:
      - echo Installing RSpec...
      - gem install rspec
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Ruby code...
      - rspec HelloWorld_spec.rb 
  post_build:
    commands:
      - echo Build from Project $ProjectName completed on `date` creating artificat $artifactName in S3
artifacts:
  files:
    - HelloWorld.rb
